### ISSUE TITLE
Remove code rather than commenting it out

### ISSUE THREAD

**Issue by benorgan** [redacademy/fitness-winter-2019#10]
If you don't need this code then please remove it rather than commenting it out. It's bad practice to comment out things using HTML comments because the markup will still appear in the browser (but will just be commented out) - this can lead to security issues

https://github.com/redacademy/fitness-winter-2019/blob/5d90190f606b0dbbcad88dd733090ed2178281f9/themes/intrafitness/template-parts/content-recent-post.php#L34-L39

**Comment by amarquesmoura** [comment]
Done.
