### ISSUE TITLE
Set images as featured image rather than hardcoding URLs in CSS

### ISSUE THREAD

**Issue by benorgan** [redacademy/fitness-winter-2019#3]
Please change the main image of the page to be the featured image rather than hardcoding URLs in the CSS where possible. 

For example in your content-page.php you can do something like:

`<div style="background-image:url(<?php echo get_the_post_thumbnail_url(); ?>)"></div>`

**Comment by benorgan** [comment]
An example would be for this page https://fitness.van.cp.academy.red/?page_id=13

**Comment by amarquesmoura** [comment]
We did this were possible. Some pages needed to be hard coded due to advanced styling.
